import { View, Text, ScrollView,StyleSheet,Button } from 'react-native'
import React, { useState, useEffect } from 'react'
import MapView, { Callout, Circle, Marker } from 'react-native-maps'
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';
import * as Location from 'expo-location'

import BusinessProfilePOPUP_Map from './ClientScreen/BusinessProfilePOPUP_Map';
// const result=[
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 0.0,
//         "End_time": 8.75,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 6.5,
//         "End_time": 16.5,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 6.75,
//         "End_time": 12.75,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 7.0,
//         "End_time": 9.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 7.5,
//         "End_time": 16.5,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 8.0,
//         "End_time": 12.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 16.0,
//         "End_time": 20.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 16.0,
//         "End_time": 20.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 8.0,
//         "End_time": 13.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 15.0,
//         "End_time": 17.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-04T00:00:00",
//         "Start_time": 20.0,
//         "End_time": 22.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-21T00:00:00",
//         "Start_time": 10.0,
//         "End_time": 15.3,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-30T00:00:00",
//         "Start_time": 6.25,
//         "End_time": 21.25,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-30T00:00:00",
//         "Start_time": 10.0,
//         "End_time": 16.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-07-01T00:00:00",
//         "Start_time": 16.5,
//         "End_time": 23.5,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1169,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 17.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-09-01T00:00:00",
//         "Start_time": 7.5,
//         "End_time": 16.5,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 0.0,
//         "End_time": 8.75,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 6.5,
//         "End_time": 16.5,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 6.75,
//         "End_time": 12.75,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 7.0,
//         "End_time": 9.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 7.5,
//         "End_time": 16.5,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 8.0,
//         "End_time": 12.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "0001-01-01T00:00:00",
//         "Start_time": 16.0,
//         "End_time": 20.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 16.0,
//         "End_time": 20.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 8.0,
//         "End_time": 13.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 15.0,
//         "End_time": 17.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-04T00:00:00",
//         "Start_time": 20.0,
//         "End_time": 22.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-21T00:00:00",
//         "Start_time": 10.0,
//         "End_time": 15.3,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-30T00:00:00",
//         "Start_time": 6.25,
//         "End_time": 21.25,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-06-30T00:00:00",
//         "Start_time": 10.0,
//         "End_time": 16.0,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-07-01T00:00:00",
//         "Start_time": 16.5,
//         "End_time": 23.5,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1170,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 4,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 19.0,
//         "End_Hour": 20.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 4,
//         "Price": 100.0000,
//         "Treatment_duration": "01:00:00",
//         "duration": 1.0,
//         "Business_id": 4,
//         "Date1": "2023-09-01T00:00:00",
//         "Start_time": 7.5,
//         "End_time": 16.5,
//         "Business_Number2": 4,
//         "Name": "עולם היופי",
//         "AddressStreet": "פנחס לבון",
//         "AddressCity": "נתניה ",
//         "Is_client_house1": "YES",
//         "Professional_ID_number": "123455555 ",
//         "About": "עולם היופי של נתניה",
//         "phone": "0524744380",
//         "Facebook_link": "https://www.facebook.com/ofir.bidani/",
//         "Instagram_link": "https://www.instagram.com/ofir_bidani1/",
//         "AddressHouseNumber": "16",
//         "LetCordinate": 32.2838812,
//         "LongCordinate": 34.8540928
//     },
//     {
//         "Number_appointment": 1171,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "NO        ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 8.0,
//         "End_Hour": 10.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 8.0,
//         "End_time": 10.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1171,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "NO        ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 8.0,
//         "End_Hour": 10.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 14.0,
//         "End_time": 20.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1171,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "NO        ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 8.0,
//         "End_Hour": 10.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 1.0,
//         "End_time": 12.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1171,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "NO        ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 8.0,
//         "End_Hour": 10.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 14.0,
//         "End_time": 20.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1173,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "NO        ",
//         "Business_Number": 1049,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 16.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 8.0,
//         "End_time": 10.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1173,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "NO        ",
//         "Business_Number": 1049,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 16.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 14.0,
//         "End_time": 20.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1173,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "NO        ",
//         "Business_Number": 1049,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 16.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 1.0,
//         "End_time": 12.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1173,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "NO        ",
//         "Business_Number": 1049,
//         "Appointment_status": "confirmed",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 16.0,
//         "End_Hour": 18.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 14.0,
//         "End_time": 20.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1195,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 12.0,
//         "End_Hour": 14.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 8.0,
//         "End_time": 10.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1195,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 12.0,
//         "End_Hour": 14.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 14.0,
//         "End_time": 20.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1195,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 12.0,
//         "End_Hour": 14.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 1.0,
//         "End_time": 12.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1195,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 12.0,
//         "End_Hour": 14.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 14.0,
//         "End_time": 20.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1196,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 10.0,
//         "End_Hour": 12.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 8.0,
//         "End_time": 10.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1196,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 10.0,
//         "End_Hour": 12.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-02T00:00:00",
//         "Start_time": 14.0,
//         "End_time": 20.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1196,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 10.0,
//         "End_Hour": 12.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 1.0,
//         "End_time": 12.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     },
//     {
//         "Number_appointment": 1196,
//         "Date": "2023-06-02T00:00:00",
//         "Is_client_house": "YES       ",
//         "Business_Number": 1049,
//         "Appointment_status": "Awaiting_approval",
//         "ID_Client": "123456789 ",
//         "Start_Hour": 10.0,
//         "End_Hour": 12.0,
//         "Type_treatment_Number": 3,
//         "Category_Number": 1,
//         "Business_Number1": 1049,
//         "Price": 130.0000,
//         "Treatment_duration": "02:00:00",
//         "duration": 2.0,
//         "Business_id": 1049,
//         "Date1": "2023-06-03T00:00:00",
//         "Start_time": 14.0,
//         "End_time": 20.0,
//         "Business_Number2": 1049,
//         "Name": "By Neta",
//         "AddressStreet": "פרישמן",
//         "AddressCity": "תל אביב",
//         "Is_client_house1": "NO ",
//         "Professional_ID_number": "308547631 ",
//         "About": null,
//         "phone": null,
//         "Facebook_link": null,
//         "Instagram_link": null,
//         "AddressHouseNumber": "39",
//         "LetCordinate": 32.0798131,
//         "LongCordinate": 34.773688
//     }
// ]
export default function Maps_Inbar({ route }) {
    const { result } = route.params;
    console.log(result)
    const Google_Api = "AIzaSyBuYjLYxY6iSSVfQ755luh6KPM0mD4QfrM";

    const [pickedLocation, setPickedLocation] = useState({ lat: '', lng: '' });
    const [location, setLocation] = useState();

    const [businessProfilePOPUP, SetBusinessProfilePOPUP] = useState(false);
    const [modalVisible, SetModalVisible] = useState(false);
    // const [locationPermissionInformation, requestPermission]= useForegroundPermissions();
    const [pin, setPin] = useState({
        latitude: 32.34245547297243,
        longitude: 34.911549397360595
    })

    const [region, setRegion] = useState({
        latitude: '',
        longitude: '',
        latitudeDelta: 0.0125,
        longitudeDelta: 0.0121,
    })
    useEffect(() => {
        (async () => {
            let { status } = await Location.requestForegroundPermissionsAsync();
            console.log(status, "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
            if (status !== 'granted') {
                console.log('Permission to access location was denied');
                alert('Go to setting and turn on access location for using this page')
                return;
            }
            let location = await Location.getCurrentPositionAsync({});
            console.log(location, "##############################################")
            setLocation(location)
            setRegion({
                latitude: Number(location.coords.latitude),
                longitude: Number(location.coords.longitude),
                latitudeDelta: 0.0125,
                longitudeDelta: 0.0121,
            });
            setPin({
                latitude: location && Number(location.coords.latitude),
                longitude: location && Number(location.coords.longitude)
            })
        })
            ();
    }, []);
    function handleBusinessProfilePOPUP() {
        console.log("open pop-up window");
        SetModalVisible(!modalVisible);
        console.log("modalVisible - ", modalVisible);
        SetBusinessProfilePOPUP(!businessProfilePOPUP);
        console.log("businessProfilePOPUP - ", businessProfilePOPUP);
        console.log("business number: " + JSON.stringify(result.id));
      }
    return (
        <View style={{ flex: 1, backgroundColor: '#4B0082' }}>
            {/* <GooglePlacesAutocomplete
                placeholder='Search...'
                autoFocus={true}
                fetchDetails={true}
                GooglePlacesSearchQuery={{
                    rankby: 'distance',
                    types: 'gym',
                }}
                onPress={(data, details = null) => {
                    console.log(data, details, "*******************************");
                    setPin({
                        latitude: details.geometry.location.lat,
                        longitude: details.geometry.location.lng,
                    })
                }}
                query={{
                    key: Google_Api,
                    language: 'en',
                    components: "country:il",
                    radius: 10000,
                    location: `${Number(region.latitude ? region.latitude : 32.34245547297243)}, ${Number(region.longitude ? region.longitude : 34.911549397360595)}`
                }}
            /> */}
            <MapView
                loadingEnabled={true}
                style={{ flex: 9, top: '1%' }}
                initialRegion={{
                    latitude: Number(location && location.coords.latitude ? location.coords.longitude : 32.166313),
                    longitude: Number(location && location.coords.longitude ? location.coords.longitude : 34.843311),
                    latitudeDelta: 0.0125,
                    longitudeDelta: 0.0121,
                }}>
                <Marker
                    coordinate={region}
                    title="אתה נמצא כאן" />
                <Marker
                    coordinate={pin}
                    pinColor='red'
                    draggable={true}
                    onDragStart={(e) => { console.log("Drag start:", Number(e.nativeEvent.coordinate)); }}
                    onDragEnd={(e) => {
                        setPin({
                            latitude: Number(e.nativeEvent.coordinate.latitude),
                            longitude: Number(e.nativeEvent.coordinate.longitude)
                        })
                    }}>
                </Marker>
                <Circle
                    center={region}
                    radius={1}
                />
                {result && result.map(x => {
                    console.log(x, "nmappppppppppppppppppppppp")
                    if (x.LetCordinate && x.LongCordinate) {
                        return (
                            <Marker
                                key={Number(x.LetCordinate)}
                                coordinate={{
                                    latitude: Number(x.LetCordinate),
                                    longitude: Number(x.LongCordinate)
                                }}
                                pinColor='#800080'
                                draggable={true}
                            >
                                <Callout>
                                    <ScrollView horizontal={true}>
                                        <Button
                                            color={"rgb(92, 71, 205)"}
                                            title="צפה בפרופיל העסק"
                                            buttonStyle={styles.buttonStyle}
                                            titleStyle={styles.buttonTitle}
                                            onPress={handleBusinessProfilePOPUP}
                                        />
                                        {businessProfilePOPUP && (
                                            < BusinessProfilePOPUP_Map
                                                x={x}
                                                isVisible={modalVisible}
                                                onClose={handleBusinessProfilePOPUP}
                                                Business_Number={x.id}
                                            />
                                        )}

                                    </ScrollView>
                                </Callout>
                            </Marker>
                        )
                    }
                })}
            </MapView>
        </View>
    )
}
const styles = StyleSheet.create({
    buttonStyle: {
        fontSize: 18, // שינוי הגודל
        color: "white", // שינוי הצבע
        fontWeight: "bold", // הופך את הטקסט לבולט
        textShadowColor: "rgba(0, 0, 0, 0.75)", // צללה שחורה
        textShadowOffset: { width: -1, height: 1 },
        textShadowRadius: 10,
     
      },
      buttonTitle: {
        fontSize: 18, // שינוי הגודל
        color: "white", // שינוי הצבע
        fontWeight: "bold", // הופך את הטקסט לבולט
        textShadowColor: "rgba(0, 0, 0, 0.75)", // צללה שחורה
        textShadowOffset: { width: -1, height: 1 },
        textShadowRadius: 10,
      },
   
  });